; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG92200 DB	'calc', 00H
CONST	ENDS
PUBLIC	?get_peb@native@@YAPEAU_PEB@1@XZ		; native::get_peb
PUBLIC	?find_module@native@@YAPEAXI@Z			; native::find_module
PUBLIC	??$r_hash@_W@@YAIPEA_W@Z			; r_hash<wchar_t>
PUBLIC	?find_kernel32@native@@YAPEAXXZ			; native::find_kernel32
PUBLIC	?find_function@native@@YAPEAXPEAXI@Z		; native::find_function
PUBLIC	??$r_hash@D@@YAIPEAD@Z				; r_hash<char>
PUBLIC	main
;	COMDAT pdata
pdata	SEGMENT
$pdata$?find_function@native@@YAPEAXPEAXI@Z DD imagerel $LN23
	DD	imagerel $LN23+129
	DD	imagerel $unwind$?find_function@native@@YAPEAXPEAXI@Z
pdata	ENDS
pdata	SEGMENT
$pdata$main DD	imagerel $LN8
	DD	imagerel $LN8+59
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?find_function@native@@YAPEAXPEAXI@Z DD 040a01H
	DD	02740aH
	DD	013405H
xdata	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	00H
voltbl	ENDS
voltbl	SEGMENT
_volmd	DDSymXIndex: 	FLAT:main
	DD	04H
_volmd	DDSymXIndex: 	FLAT:?find_module@native@@YAPEAXI@Z
	DD	00H
voltbl	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	00H
voltbl	ENDS
; Function compile flags: /Ogspy
_TEXT	SEGMENT
main	PROC
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 11
$LN8:
	sub	rsp, 40					; 00000028H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 11
	mov	rax, QWORD PTR gs:96
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	mov	edx, 698766968				; 29a65678H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 69
	mov	rcx, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rcx+32]
	mov	rcx, QWORD PTR [rax]
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	mov	rcx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR [rcx+32]
	call	?find_function@native@@YAPEAXPEAXI@Z	; native::find_function
; Line 18
	xor	edx, edx
	lea	rcx, OFFSET FLAT:$SG92200
	call	rax
; Line 19
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@D@@YAIPEAD@Z
_TEXT	SEGMENT
str$ = 8
??$r_hash@D@@YAIPEAD@Z PROC				; r_hash<char>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 21
	mov	eax, 5381				; 00001505H
; Line 22
	jmp	SHORT $LN10@r_hash
$LL2@r_hash:
; Line 23
	imul	eax, eax, 33				; 00000021H
	add	eax, edx
$LN10@r_hash:
; Line 22
	movsx	edx, BYTE PTR [rcx]
	inc	rcx
	test	edx, edx
	jne	SHORT $LL2@r_hash
; Line 25
	ret	0
??$r_hash@D@@YAIPEAD@Z ENDP				; r_hash<char>
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_function@native@@YAPEAXPEAXI@Z
_TEXT	SEGMENT
mod$ = 8
hash$ = 16
?find_function@native@@YAPEAXPEAXI@Z PROC		; native::find_function, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 76
$LN23:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rdi
; Line 79
	movsxd	rax, DWORD PTR [rcx+60]
; Line 86
	xor	r10d, r10d
	mov	ebx, edx
	mov	r8, rcx
	mov	r9d, DWORD PTR [rax+rcx+136]
	add	r9, rcx
	cmp	DWORD PTR [r9+24], r10d
	jbe	SHORT $LN3@find_funct
	mov	edi, DWORD PTR [r9+32]
$LL4@find_funct:
; Line 89
	lea	rax, QWORD PTR [rdi+r10*4]
; Line 92
	mov	ecx, DWORD PTR [rax+r8]
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 21
	mov	eax, 5381				; 00001505H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 92
	add	rcx, r8
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 22
	jmp	SHORT $LN21@find_funct
$LL8@find_funct:
; Line 23
	imul	eax, eax, 33				; 00000021H
	add	eax, edx
$LN21@find_funct:
; Line 22
	movsx	edx, BYTE PTR [rcx]
	inc	rcx
	test	edx, edx
	jne	SHORT $LL8@find_funct
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 92
	cmp	eax, ebx
	je	SHORT $LN13@find_funct
; Line 86
	inc	r10d
	cmp	r10d, DWORD PTR [r9+24]
	jb	SHORT $LL4@find_funct
$LN3@find_funct:
; Line 103
	xor	eax, eax
$LN1@find_funct:
; Line 104
	mov	rbx, QWORD PTR [rsp+8]
	mov	rdi, QWORD PTR [rsp+16]
	ret	0
$LN13@find_funct:
; Line 95
	mov	ecx, DWORD PTR [r9+36]
	add	rcx, r8
; Line 96
	movzx	edx, WORD PTR [rcx+r10*2]
	mov	ecx, DWORD PTR [r9+28]
	add	rcx, r8
; Line 99
	mov	eax, DWORD PTR [rcx+rdx*4]
	add	rax, r8
	jmp	SHORT $LN1@find_funct
?find_function@native@@YAPEAXPEAXI@Z ENDP		; native::find_function
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_kernel32@native@@YAPEAXXZ
_TEXT	SEGMENT
?find_kernel32@native@@YAPEAXXZ PROC			; native::find_kernel32, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 11
	mov	rax, QWORD PTR gs:96
; Line 69
	mov	rcx, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rcx+32]
	mov	rcx, QWORD PTR [rax]
; Line 72
	mov	rax, QWORD PTR [rcx]
	mov	rax, QWORD PTR [rax+32]
; Line 73
	ret	0
?find_kernel32@native@@YAPEAXXZ ENDP			; native::find_kernel32
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@_W@@YAIPEA_W@Z
_TEXT	SEGMENT
str$ = 8
??$r_hash@_W@@YAIPEA_W@Z PROC				; r_hash<wchar_t>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 22
	movzx	edx, WORD PTR [rcx]
	mov	eax, 5381				; 00001505H
	add	rcx, 2
	jmp	SHORT $LN9@r_hash
$LL2@r_hash:
; Line 23
	imul	eax, eax, 33				; 00000021H
	add	eax, edx
	movzx	edx, WORD PTR [rcx]
	lea	rcx, QWORD PTR [rcx+2]
$LN9@r_hash:
; Line 22
	test	edx, edx
	jne	SHORT $LL2@r_hash
; Line 25
	ret	0
??$r_hash@_W@@YAIPEA_W@Z ENDP				; r_hash<wchar_t>
_TEXT	ENDS
; Function compile flags: /Ogspy
_TEXT	SEGMENT
hash$ = 8
?find_module@native@@YAPEAXI@Z PROC			; native::find_module
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 11
	mov	rax, QWORD PTR gs:96
; Line 24
	mov	rdx, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rdx+16]
; Line 27
	mov	r10, rax
$LL4@find_modul:
; Line 33
	mov	rdx, QWORD PTR [rax+96]
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 21
	mov	r8d, 5381				; 00001505H
; Line 22
	movzx	r9d, WORD PTR [rdx]
	add	rdx, 2
	jmp	SHORT $LN22@find_modul
$LL11@find_modul:
; Line 23
	imul	r8d, r8d, 33				; 00000021H
	add	r8d, r9d
	movzx	r9d, WORD PTR [rdx]
	lea	rdx, QWORD PTR [rdx+2]
$LN22@find_modul:
; Line 22
	test	r9d, r9d
	jne	SHORT $LL11@find_modul
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 33
	cmp	r8d, ecx
	je	SHORT $LN16@find_modul
; Line 37
	mov	rax, QWORD PTR [rax]
; Line 39
	test	rax, rax
	je	SHORT $LN6@find_modul
	cmp	rax, r10
	jne	SHORT $LL4@find_modul
$LN6@find_modul:
; Line 41
	xor	eax, eax
; Line 42
	ret	0
$LN16@find_modul:
; Line 34
	mov	rax, QWORD PTR [rax+48]
; Line 42
	ret	0
?find_module@native@@YAPEAXI@Z ENDP			; native::find_module
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?get_peb@native@@YAPEAU_PEB@1@XZ
_TEXT	SEGMENT
?get_peb@native@@YAPEAU_PEB@1@XZ PROC			; native::get_peb, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 11
	mov	rax, QWORD PTR gs:96
; Line 15
	ret	0
?get_peb@native@@YAPEAU_PEB@1@XZ ENDP			; native::get_peb
_TEXT	ENDS
END
