; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

PUBLIC	?find_function@native@@YAPEAXPEAXI@Z		; native::find_function
PUBLIC	??$r_hash@D@@YAIPEAD@Z				; r_hash<char>
PUBLIC	main

; Function compile flags: /Ogspy
PUBLIC  AlignRSP
_TEXT SEGMENT
	; AlignRSP - by @mattifestation (http://www.exploit-monday.com/2013/08/writing-optimized-windows-shellcode-in-c.html)
	; AlignRSP is a simple call stub that ensures that the stack is 16 - byte aligned prior
	; to calling the entry point of the payload.This is necessary because 64 - bit functions
	; in Windows assume that they were called with 16 - byte stack alignment.When amd64
	; shellcode is executed, you can't be assured that you stack is 16-byte aligned. For example,
	; if your shellcode lands with 8 - byte stack alignment, any call to a Win32 function will likely
	; crash upon calling any ASM instruction that utilizes XMM registers(which require 16 - byte)
	; alignment.

	AlignRSP PROC
	push rsi; Preserve RSI since we're stomping on it
	mov  rsi, rsp; Save the value of RSP so it can be restored
	and  rsp, 0FFFFFFFFFFFFFFF0h; Align RSP to 16 bytes
	sub  rsp, 020h; Allocate homing space for ExecutePayload
	call main; Call the entry point of the payload
	mov  rsp, rsi; Restore the original value of RSP
	pop  rsi; Restore RSI
	ret; Return to caller
	AlignRSP ENDP
_TEXT ENDS

_TEXT	SEGMENT
main	PROC
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 11
$LN8:
	sub	rsp, 40					; 00000028H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 11
	mov	rax, QWORD PTR gs:[96]
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	mov	edx, 698766968				; 29a65678H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 69
	mov	rcx, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rcx+32]
	mov	rcx, QWORD PTR [rax]
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	mov	rcx, QWORD PTR [rcx]
	mov	rcx, QWORD PTR [rcx+32]
	call	?find_function@native@@YAPEAXPEAXI@Z	; native::find_function
; Line 18
	xor	edx, edx
	CALL after_$SG92200
$SG92200 DB	'calc', 00H
after_$SG92200:
	POP  rcx

; 	lea	rcx, OFFSET FLAT:$SG92200
	call	rax
; Line 19
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@D@@YAIPEAD@Z
_TEXT	SEGMENT
str$ = 8
??$r_hash@D@@YAIPEAD@Z PROC				; r_hash<char>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 21
	mov	eax, 5381				; 00001505H
; Line 22
	jmp	SHORT $LN10@r_hash
$LL2@r_hash:
; Line 23
	imul	eax, eax, 33				; 00000021H
	add	eax, edx
$LN10@r_hash:
; Line 22
	movsx	edx, BYTE PTR [rcx]
	inc	rcx
	test	edx, edx
	jne	SHORT $LL2@r_hash
; Line 25
	ret	0
??$r_hash@D@@YAIPEAD@Z ENDP				; r_hash<char>
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_function@native@@YAPEAXPEAXI@Z
_TEXT	SEGMENT
mod$ = 8
hash$ = 16
?find_function@native@@YAPEAXPEAXI@Z PROC		; native::find_function, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 76
$LN23:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rdi
; Line 79
	movsxd	rax, DWORD PTR [rcx+60]
; Line 86
	xor	r10d, r10d
	mov	ebx, edx
	mov	r8, rcx
	mov	r9d, DWORD PTR [rax+rcx+136]
	add	r9, rcx
	cmp	DWORD PTR [r9+24], r10d
	jbe	SHORT $LN3@find_funct
	mov	edi, DWORD PTR [r9+32]
$LL4@find_funct:
; Line 89
	lea	rax, QWORD PTR [rdi+r10*4]
; Line 92
	mov	ecx, DWORD PTR [rax+r8]
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 21
	mov	eax, 5381				; 00001505H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 92
	add	rcx, r8
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 22
	jmp	SHORT $LN21@find_funct
$LL8@find_funct:
; Line 23
	imul	eax, eax, 33				; 00000021H
	add	eax, edx
$LN21@find_funct:
; Line 22
	movsx	edx, BYTE PTR [rcx]
	inc	rcx
	test	edx, edx
	jne	SHORT $LL8@find_funct
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 92
	cmp	eax, ebx
	je	SHORT $LN13@find_funct
; Line 86
	inc	r10d
	cmp	r10d, DWORD PTR [r9+24]
	jb	SHORT $LL4@find_funct
$LN3@find_funct:
; Line 103
	xor	eax, eax
$LN1@find_funct:
; Line 104
	mov	rbx, QWORD PTR [rsp+8]
	mov	rdi, QWORD PTR [rsp+16]
	ret	0
$LN13@find_funct:
; Line 95
	mov	ecx, DWORD PTR [r9+36]
	add	rcx, r8
; Line 96
	movzx	edx, WORD PTR [rcx+r10*2]
	mov	ecx, DWORD PTR [r9+28]
	add	rcx, r8
; Line 99
	mov	eax, DWORD PTR [rcx+rdx*4]
	add	rax, r8
	jmp	SHORT $LN1@find_funct
?find_function@native@@YAPEAXPEAXI@Z ENDP		; native::find_function
_TEXT	ENDS
END
